import { DEFAULT_THEME_ID } from '$lib/constants';

export interface Theme {
  name: string;
  // Colors
  canvasBg: string;
  cardBg: string;
  panelBg: string;
  surfaceBorder: string;
  infraAccent: string;
  agentAccent: string;
  alertAccent: string;
  successAccent: string;
  warningAccent: string;
  textPrimary: string;
  textSecondary: string;
  textMuted: string;
  // Typography
  fontFamily: string;
  monoFamily: string;
  textTransform: string;
  headingWeight: number;
  bodyWeight: number;
  letterSpacing: 'tight' | 'normal' | 'wide';
  // Borders
  borderRadius: string;
  borderWidth: string;
  borderStyle: 'solid' | 'dashed' | 'double' | 'dotted' | 'ridge' | 'none';
  borderOpacity: number;
  // Surface & Card Treatment
  surfaceTreatment: 'flat' | 'glass' | 'elevated' | 'inset';
  cardShadow: string;
  surfaceOpacity: number;
  backdropBlur: string;
  // Effects & Animation
  glowIntensity: number;
  glowColor: string;
  transitionSpeed: 'fast' | 'normal' | 'slow';
}

export const THEMES: Record<string, Theme> = {
  // ============================================================
  // CORE THEMES
  // ============================================================

  slate: {
    name: 'Slate',
    canvasBg: '#0f172a',
    cardBg: '#1e293b',
    panelBg: '#1e293b',
    surfaceBorder: '#334155',
    infraAccent: '#6366f1',
    agentAccent: '#06b6d4',
    alertAccent: '#ef4444',
    successAccent: '#22c55e',
    warningAccent: '#f59e0b',
    textPrimary: '#e2e8f0',
    textSecondary: '#94a3b8',
    textMuted: '#64748b',
    fontFamily: "'Rajdhani', system-ui, sans-serif",
    monoFamily: "'JetBrains Mono', monospace",
    textTransform: 'none',
    borderRadius: '8px',
    borderWidth: '1px',
    surfaceTreatment: 'flat',
    cardShadow: '0 2px 8px rgba(0,0,0,0.3)',
    surfaceOpacity: 1.0,
    backdropBlur: '0px',
    borderStyle: 'solid',
    borderOpacity: 1.0,
    headingWeight: 600,
    bodyWeight: 400,
    letterSpacing: 'normal',
    glowIntensity: 0.6,
    glowColor: '#06b6d4',
    transitionSpeed: 'normal',
  },
  holt: {
    name: 'Holt',
    canvasBg: '#080c14',
    cardBg: '#0e1420',
    panelBg: '#0e1420',
    surfaceBorder: '#1a2538',
    infraAccent: '#3b82f6',
    agentAccent: '#10b981',
    alertAccent: '#f43f5e',
    successAccent: '#34d399',
    warningAccent: '#fbbf24',
    textPrimary: '#d1dbe8',
    textSecondary: '#7a8da4',
    textMuted: '#4a5c72',
    fontFamily: "'Rajdhani', system-ui, sans-serif",
    monoFamily: "'JetBrains Mono', monospace",
    textTransform: 'none',
    borderRadius: '6px',
    borderWidth: '1px',
    surfaceTreatment: 'flat',
    cardShadow: '0 2px 10px rgba(0,0,0,0.25)',
    surfaceOpacity: 1.0,
    backdropBlur: '0px',
    borderStyle: 'solid',
    borderOpacity: 1.0,
    headingWeight: 600,
    bodyWeight: 400,
    letterSpacing: 'normal',
    glowIntensity: 0.5,
    glowColor: '#22c55e',
    transitionSpeed: 'normal',
  },
  arctic: {
    name: 'Arctic',
    canvasBg: '#f0f4f8',
    cardBg: '#ffffff',
    panelBg: '#f7f9fc',
    surfaceBorder: '#d0dae6',
    infraAccent: '#2563eb',
    agentAccent: '#0284c7',
    alertAccent: '#dc2626',
    successAccent: '#059669',
    warningAccent: '#ca8a04',
    textPrimary: '#0f1729',
    textSecondary: '#475569',
    textMuted: '#94a3b8',
    fontFamily: "'Rajdhani', system-ui, sans-serif",
    monoFamily: "'JetBrains Mono', monospace",
    textTransform: 'none',
    borderRadius: '10px',
    borderWidth: '1px',
    surfaceTreatment: 'elevated',
    cardShadow: '0 1px 6px rgba(0,0,0,0.06)',
    surfaceOpacity: 1.0,
    backdropBlur: '0px',
    borderStyle: 'solid',
    borderOpacity: 0.6,
    headingWeight: 500,
    bodyWeight: 400,
    letterSpacing: 'normal',
    glowIntensity: 0.3,
    glowColor: '#38bdf8',
    transitionSpeed: 'normal',
  },

  // ============================================================
  // MINIMAL THEMES
  // ============================================================

  oxide: {
    name: 'Oxide',
    canvasBg: '#111111',
    cardBg: '#1a1a1a',
    panelBg: '#1a1a1a',
    surfaceBorder: '#2e2e2e',
    infraAccent: '#a3a3a3',
    agentAccent: '#d4d4d4',
    alertAccent: '#f87171',
    successAccent: '#86efac',
    warningAccent: '#fde68a',
    textPrimary: '#e5e5e5',
    textSecondary: '#8a8a8a',
    textMuted: '#525252',
    fontFamily: "'Rajdhani', system-ui, sans-serif",
    monoFamily: "'JetBrains Mono', monospace",
    textTransform: 'none',
    borderRadius: '2px',
    borderWidth: '1px',
    surfaceTreatment: 'flat',
    cardShadow: 'none',
    surfaceOpacity: 1.0,
    backdropBlur: '0px',
    borderStyle: 'solid',
    borderOpacity: 0.4,
    headingWeight: 500,
    bodyWeight: 400,
    letterSpacing: 'normal',
    glowIntensity: 0,
    glowColor: '#a1a1aa',
    transitionSpeed: 'fast',
  },
  void: {
    name: 'Void',
    canvasBg: '#000000',
    cardBg: '#0a0a0a',
    panelBg: '#0a0a0a',
    surfaceBorder: '#1a1a1a',
    infraAccent: '#6366f1',
    agentAccent: '#818cf8',
    alertAccent: '#f87171',
    successAccent: '#a5b4fc',
    warningAccent: '#c4b5fd',
    textPrimary: '#d4d4d8',
    textSecondary: '#71717a',
    textMuted: '#3f3f46',
    fontFamily: "'Rajdhani', system-ui, sans-serif",
    monoFamily: "'JetBrains Mono', monospace",
    textTransform: 'none',
    borderRadius: '4px',
    borderWidth: '1px',
    surfaceTreatment: 'flat',
    cardShadow: 'none',
    surfaceOpacity: 1.0,
    backdropBlur: '0px',
    borderStyle: 'solid',
    borderOpacity: 0.3,
    headingWeight: 500,
    bodyWeight: 400,
    letterSpacing: 'normal',
    glowIntensity: 0,
    glowColor: '#6366f1',
    transitionSpeed: 'fast',
  },

  // ============================================================
  // GLASS THEMES
  // ============================================================

  aurora: {
    name: 'Aurora',
    canvasBg: '#0d0a14',
    cardBg: '#161024',
    panelBg: '#161024',
    surfaceBorder: '#2a1f3d',
    infraAccent: '#7c3aed',
    agentAccent: '#f97316',
    alertAccent: '#ef4444',
    successAccent: '#06d6a0',
    warningAccent: '#fbbf24',
    textPrimary: '#f0e6d8',
    textSecondary: '#9b8ab8',
    textMuted: '#5c4a75',
    fontFamily: "'Rajdhani', system-ui, sans-serif",
    monoFamily: "'JetBrains Mono', monospace",
    textTransform: 'none',
    borderRadius: '8px',
    borderWidth: '1px',
    surfaceTreatment: 'glass',
    cardShadow: '0 8px 32px rgba(168,85,247,0.2)',
    surfaceOpacity: 0.7,
    backdropBlur: '12px',
    borderStyle: 'none',
    borderOpacity: 0,
    headingWeight: 500,
    bodyWeight: 300,
    letterSpacing: 'wide',
    glowIntensity: 0.8,
    glowColor: '#a855f7',
    transitionSpeed: 'slow',
  },
  'aurora-light': {
    name: 'Aurora Light',
    canvasBg: '#faf7f2',
    cardBg: '#ffffff',
    panelBg: '#fefcf9',
    surfaceBorder: '#e8ddd0',
    infraAccent: '#7c3aed',
    agentAccent: '#ea580c',
    alertAccent: '#dc2626',
    successAccent: '#0891b2',
    warningAccent: '#d97706',
    textPrimary: '#2d1b4e',
    textSecondary: '#6b5a85',
    textMuted: '#a099ad',
    fontFamily: "'Rajdhani', system-ui, sans-serif",
    monoFamily: "'JetBrains Mono', monospace",
    textTransform: 'none',
    borderRadius: '8px',
    borderWidth: '1px',
    surfaceTreatment: 'glass',
    cardShadow: '0 4px 20px rgba(168,85,247,0.1)',
    surfaceOpacity: 0.8,
    backdropBlur: '10px',
    borderStyle: 'none',
    borderOpacity: 0,
    headingWeight: 500,
    bodyWeight: 300,
    letterSpacing: 'wide',
    glowIntensity: 0.6,
    glowColor: '#a855f7',
    transitionSpeed: 'slow',
  },
  crystalline: {
    name: 'Crystalline',
    canvasBg: '#060A10',
    cardBg: '#0C1420',
    panelBg: '#0C1420',
    surfaceBorder: '#1A2840',
    infraAccent: '#7DD3FC',
    agentAccent: '#A5B4FC',
    alertAccent: '#F87171',
    successAccent: '#67E8F9',
    warningAccent: '#FDE68A',
    textPrimary: '#E8F0FA',
    textSecondary: '#7AA0C4',
    textMuted: '#3A5670',
    fontFamily: "'Rajdhani', system-ui, sans-serif",
    monoFamily: "'JetBrains Mono', monospace",
    textTransform: 'none',
    borderRadius: '10px',
    borderWidth: '1px',
    surfaceTreatment: 'glass',
    cardShadow: '0 8px 32px rgba(125,211,252,0.08)',
    surfaceOpacity: 0.6,
    backdropBlur: '16px',
    borderStyle: 'solid',
    borderOpacity: 0.3,
    headingWeight: 300,
    bodyWeight: 300,
    letterSpacing: 'wide',
    glowIntensity: 0.5,
    glowColor: '#7DD3FC',
    transitionSpeed: 'slow',
  },
  neon: {
    name: 'Neon',
    canvasBg: '#05020A',
    cardBg: '#0F0818',
    panelBg: '#0F0818',
    surfaceBorder: '#2A1040',
    infraAccent: '#F400A1',
    agentAccent: '#00F0FF',
    alertAccent: '#FF2D2D',
    successAccent: '#00FF88',
    warningAccent: '#FFE500',
    textPrimary: '#F0E8F4',
    textSecondary: '#B080D0',
    textMuted: '#5A3070',
    fontFamily: "'Rajdhani', system-ui, sans-serif",
    monoFamily: "'JetBrains Mono', monospace",
    textTransform: 'none',
    borderRadius: '8px',
    borderWidth: '1px',
    surfaceTreatment: 'glass',
    cardShadow: '0 4px 20px rgba(244,0,161,0.2), 0 0 40px rgba(0,240,255,0.05)',
    surfaceOpacity: 0.75,
    backdropBlur: '12px',
    borderStyle: 'solid',
    borderOpacity: 0.6,
    headingWeight: 700,
    bodyWeight: 400,
    letterSpacing: 'tight',
    glowIntensity: 1.0,
    glowColor: '#F400A1',
    transitionSpeed: 'fast',
  },

  // ============================================================
  // NATURE THEMES
  // ============================================================

  tropical: {
    name: 'Tropical Sunset',
    canvasBg: '#0D0806',
    cardBg: '#1A1210',
    panelBg: '#1A1210',
    surfaceBorder: '#3D2A20',
    infraAccent: '#FF6B35',
    agentAccent: '#F5A623',
    alertAccent: '#EF4444',
    successAccent: '#34D399',
    warningAccent: '#FBBF24',
    textPrimary: '#FBF0E8',
    textSecondary: '#C4A88E',
    textMuted: '#7A5E48',
    fontFamily: "'Rajdhani', system-ui, sans-serif",
    monoFamily: "'JetBrains Mono', monospace",
    textTransform: 'none',
    borderRadius: '14px',
    borderWidth: '1px',
    surfaceTreatment: 'elevated',
    cardShadow: '0 6px 24px rgba(255,107,53,0.12), 0 2px 8px rgba(0,0,0,0.3)',
    surfaceOpacity: 1.0,
    backdropBlur: '0px',
    borderStyle: 'solid',
    borderOpacity: 0.5,
    headingWeight: 600,
    bodyWeight: 400,
    letterSpacing: 'normal',
    glowIntensity: 0.7,
    glowColor: '#FF6B35',
    transitionSpeed: 'slow',
  },
  canopy: {
    name: 'Canopy',
    canvasBg: '#060B06',
    cardBg: '#0D150D',
    panelBg: '#0D150D',
    surfaceBorder: '#1E3318',
    infraAccent: '#4ADE80',
    agentAccent: '#A3BE8C',
    alertAccent: '#E87461',
    successAccent: '#81C784',
    warningAccent: '#DCB468',
    textPrimary: '#D4DFD0',
    textSecondary: '#8A9E82',
    textMuted: '#4A5E44',
    fontFamily: "'Rajdhani', system-ui, sans-serif",
    monoFamily: "'JetBrains Mono', monospace",
    textTransform: 'none',
    borderRadius: '6px',
    borderWidth: '1px',
    surfaceTreatment: 'flat',
    cardShadow: '0 2px 6px rgba(0,0,0,0.4)',
    surfaceOpacity: 1.0,
    backdropBlur: '0px',
    borderStyle: 'solid',
    borderOpacity: 0.7,
    headingWeight: 500,
    bodyWeight: 400,
    letterSpacing: 'normal',
    glowIntensity: 0.3,
    glowColor: '#4ADE80',
    transitionSpeed: 'normal',
  },
  patina: {
    name: 'Patina',
    canvasBg: '#0c0f0e',
    cardBg: '#141a18',
    panelBg: '#141a18',
    surfaceBorder: '#263230',
    infraAccent: '#2dd4a8',
    agentAccent: '#d4956b',
    alertAccent: '#e87461',
    successAccent: '#4fd1c5',
    warningAccent: '#e0b870',
    textPrimary: '#d4cec4',
    textSecondary: '#8a9590',
    textMuted: '#546660',
    fontFamily: "'Rajdhani', system-ui, sans-serif",
    monoFamily: "'JetBrains Mono', monospace",
    textTransform: 'none',
    borderRadius: '3px',
    borderWidth: '1px',
    surfaceTreatment: 'flat',
    cardShadow: '0 2px 8px rgba(0,0,0,0.2)',
    surfaceOpacity: 1.0,
    backdropBlur: '0px',
    borderStyle: 'solid',
    borderOpacity: 0.7,
    headingWeight: 600,
    bodyWeight: 400,
    letterSpacing: 'normal',
    glowIntensity: 0.4,
    glowColor: '#2dd4bf',
    transitionSpeed: 'normal',
  },

  // ============================================================
  // STRUCTURAL THEMES (distinct shapes, not just recolors)
  // ============================================================

  terminal: {
    name: 'Terminal',
    canvasBg: '#020202',
    cardBg: '#0A0A0A',
    panelBg: '#0A0A0A',
    surfaceBorder: '#1A3A1A',
    infraAccent: '#00FF41',
    agentAccent: '#00D4AA',
    alertAccent: '#FF3333',
    successAccent: '#00FF41',
    warningAccent: '#FFAA00',
    textPrimary: '#00FF41',
    textSecondary: '#00AA2A',
    textMuted: '#006618',
    fontFamily: "'Share Tech Mono', monospace",
    monoFamily: "'Share Tech Mono', monospace",
    textTransform: 'none',
    borderRadius: '0px',
    borderWidth: '1px',
    surfaceTreatment: 'flat',
    cardShadow: 'none',
    surfaceOpacity: 1.0,
    backdropBlur: '0px',
    borderStyle: 'solid',
    borderOpacity: 0.5,
    headingWeight: 400,
    bodyWeight: 400,
    letterSpacing: 'normal',
    glowIntensity: 0.9,
    glowColor: '#00FF41',
    transitionSpeed: 'fast',
  },
  brutalist: {
    name: 'Brutalist',
    canvasBg: '#000000',
    cardBg: '#0A0A0A',
    panelBg: '#0A0A0A',
    surfaceBorder: '#FACC15',
    infraAccent: '#FACC15',
    agentAccent: '#FFFFFF',
    alertAccent: '#FF0000',
    successAccent: '#00FF00',
    warningAccent: '#FACC15',
    textPrimary: '#FFFFFF',
    textSecondary: '#A0A0A0',
    textMuted: '#505050',
    fontFamily: "'Share Tech Mono', monospace",
    monoFamily: "'Share Tech Mono', monospace",
    textTransform: 'uppercase',
    borderRadius: '0px',
    borderWidth: '3px',
    surfaceTreatment: 'flat',
    cardShadow: '6px 6px 0 #FACC15',
    surfaceOpacity: 1.0,
    backdropBlur: '0px',
    borderStyle: 'solid',
    borderOpacity: 1.0,
    headingWeight: 700,
    bodyWeight: 400,
    letterSpacing: 'tight',
    glowIntensity: 0,
    glowColor: '#FACC15',
    transitionSpeed: 'fast',
  },
  industrial: {
    name: 'Industrial',
    canvasBg: '#0A0908',
    cardBg: '#141210',
    panelBg: '#141210',
    surfaceBorder: '#3D3530',
    infraAccent: '#D4A574',
    agentAccent: '#A3A3A3',
    alertAccent: '#DC4444',
    successAccent: '#7AC47A',
    warningAccent: '#DCA744',
    textPrimary: '#D4CDC8',
    textSecondary: '#8A8078',
    textMuted: '#524A44',
    fontFamily: "'Share Tech Mono', monospace",
    monoFamily: "'Share Tech Mono', monospace",
    textTransform: 'uppercase',
    borderRadius: '2px',
    borderWidth: '2px',
    surfaceTreatment: 'inset',
    cardShadow: 'inset 0 1px 3px rgba(0,0,0,0.4)',
    surfaceOpacity: 1.0,
    backdropBlur: '0px',
    borderStyle: 'dashed',
    borderOpacity: 0.6,
    headingWeight: 700,
    bodyWeight: 400,
    letterSpacing: 'wide',
    glowIntensity: 0,
    glowColor: '#D4A574',
    transitionSpeed: 'fast',
  },
  soft: {
    name: 'Soft',
    canvasBg: '#0C0B12',
    cardBg: '#16141E',
    panelBg: '#16141E',
    surfaceBorder: '#2A2538',
    infraAccent: '#A78BFA',
    agentAccent: '#F9A8D4',
    alertAccent: '#FCA5A5',
    successAccent: '#86EFAC',
    warningAccent: '#FDE68A',
    textPrimary: '#E8E4F0',
    textSecondary: '#9B8AB8',
    textMuted: '#5C4A75',
    fontFamily: "'Rajdhani', system-ui, sans-serif",
    monoFamily: "'JetBrains Mono', monospace",
    textTransform: 'none',
    borderRadius: '16px',
    borderWidth: '1px',
    surfaceTreatment: 'elevated',
    cardShadow: '0 4px 16px rgba(167,139,250,0.08), 0 12px 40px rgba(0,0,0,0.15)',
    surfaceOpacity: 1.0,
    backdropBlur: '0px',
    borderStyle: 'solid',
    borderOpacity: 0.4,
    headingWeight: 400,
    bodyWeight: 300,
    letterSpacing: 'wide',
    glowIntensity: 0.4,
    glowColor: '#A78BFA',
    transitionSpeed: 'slow',
  },
};

export const DEFAULT_THEME = DEFAULT_THEME_ID;
